### Create a new blob
POST http://localhost:3000/api/jsonBlob
Content-Type: application/json

[]

### Get a blob
GET http://localhost:3000/api/jsonBlob/{{blobId}}

### Update a blob
PUT http://localhost:3000/api/jsonBlob/{{blobId}}
Content-Type: application/json

[]

### Delete a blob
DELETE http://localhost:3000/api/jsonBlob/{{blobId}} 